//! Two jobs, and they are deliberately small.
//!
//! The first is to turn the bytes of `native/viprs_acadsharp.h` into the three
//! constants the crate compares the library against: the ABI version, the wire
//! version and the fingerprint. All three are read out of the header rather
//! than typed into Rust source anywhere. A number somebody typed drifts from
//! the file it describes the first time that file changes, and it drifts in
//! the one direction that does damage, by carrying on reporting agreement.
//!
//! The second is to find the native archive, if there is one, read its
//! `metadata/LINKINFO.json`, decide whether to link it shared or static, and
//! print the exact lines that say so. That half starts at the `Archive
//! resolution and linking` banner and lives in `build/manifest.rs` (what the
//! manifest means), `build/linkinfo.rs` (the JSON, under `serde_json`) and
//! `build/policy.rs` (which way to link, as a pure function).
//!
//! The crate has to build with no archive at all, because `Check & Lint`,
//! `MSRV` and `Docs` never link one. So a missing archive is a warning and an
//! absent `cfg`, never an error, and the two link features exist but pick
//! nothing until there is an archive to pick between.

#[path = "build/header.rs"]
mod header;
#[path = "build/linkinfo.rs"]
mod linkinfo;
#[path = "build/manifest.rs"]
mod manifest;
#[path = "build/policy.rs"]
mod policy;
#[path = "build/sha256.rs"]
mod sha256;

use std::path::{Path, PathBuf};

/// The vendored header, relative to the manifest directory.
const HEADER: &str = "native/viprs_acadsharp.h";
/// The digest committed beside it, in `sha256sum` format.
const HEADER_DIGEST: &str = "native/viprs_acadsharp.h.sha256";

fn main() {
    // Emitting any rerun-if-changed turns off cargo's default "rerun when
    // anything in the package changed", so every input this script reads has
    // to be listed, this file and the hash it pulls in included.
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=build/header.rs");
    println!("cargo::rerun-if-changed=build/linkinfo.rs");
    println!("cargo::rerun-if-changed=build/manifest.rs");
    println!("cargo::rerun-if-changed=build/policy.rs");
    println!("cargo::rerun-if-changed=build/sha256.rs");
    println!("cargo::rerun-if-changed={HEADER}");
    println!("cargo::rerun-if-changed={HEADER_DIGEST}");
    println!("cargo::rerun-if-env-changed=ACADSHARP_NATIVE_DIR");
    println!("cargo::rerun-if-env-changed=ACADSHARP_REQUIRE_NATIVE");
    println!("cargo::rerun-if-env-changed=CARGO_HOME");
    // Without these every `cfg(acadsharp_linked)` in the crate is an
    // unexpected_cfgs warning, and the gate denies warnings.
    println!("cargo::rustc-check-cfg=cfg(acadsharp_linked)");
    println!("cargo::rustc-check-cfg=cfg(acadsharp_static_linked)");

    let manifest_dir = PathBuf::from(env_var("CARGO_MANIFEST_DIR"));
    let header_path = manifest_dir.join(HEADER);
    let header_bytes = std::fs::read(&header_path).unwrap_or_else(|e| {
        panic!(
            "I could not read the vendored header at {}: {e}. It is committed, so this means the \
             checkout is incomplete rather than that something needs fetching.",
            header_path.display()
        )
    });

    let digest = sha256::sha256(&header_bytes);
    verify_digest(&manifest_dir.join(HEADER_DIGEST), &sha256::hex(&digest));

    let header_text = String::from_utf8(header_bytes)
        .expect("the vendored header is not valid UTF-8, which no version of it has ever been");
    let abi_version = u32_define(&header_text, "VIPRS_ACAD_ABI_VERSION");
    let wire_version = u32_define(&header_text, "VIPRS_ACAD_WIRE_VERSION");
    // The fingerprint is the first eight bytes of the digest, big-endian, and
    // that definition lives in the header's own comment on
    // `viprs_acad_abi_fingerprint`.
    let fingerprint =
        u64::from_be_bytes(digest[..8].try_into().expect("a sha256 digest is 32 bytes"));

    let out = PathBuf::from(env_var("OUT_DIR")).join("abi_constants.rs");
    let generated = format!(
        r#"// Generated by build.rs from {HEADER}. Nothing here is typed by hand, so
// editing this file has no effect: the next build overwrites it from the
// header's bytes.

/// The VIPRS CAD ABI version the vendored header declares.
///
/// The native library reports the same number through
/// [`viprs_acad_abi_version`](crate::ffi::viprs_acad_abi_version), and a
/// disagreement is a hard refusal rather than something to negotiate at
/// runtime.
pub const EXPECTED_ABI_VERSION: u32 = {abi_version};

/// The batch protocol version the vendored header declares.
///
/// This one moves on its own. A record's payload can gain a field without a
/// single declaration in the header changing, so a consumer that only calls
/// the entry points is unaffected while a consumer that parses the stream is
/// not. Read both numbers, never infer either from the other.
pub const EXPECTED_WIRE_VERSION: u32 = {wire_version};

/// The first eight bytes of the vendored header's sha256, read big-endian.
///
/// The native library reports the same number through
/// [`viprs_acad_abi_fingerprint`](crate::ffi::viprs_acad_abi_fingerprint).
/// They differ exactly when the header and the library came from different
/// commits, which is the failure worth catching: the library loads, every
/// symbol resolves, and a struct field is four bytes from where this crate
/// believes it is.
pub const EXPECTED_ABI_FINGERPRINT: u64 = {fingerprint:#018x};
"#
    );
    std::fs::write(&out, generated)
        .unwrap_or_else(|e| panic!("I could not write {}: {e}", out.display()));

    // The one thing that crosses from the expectations half into the archive
    // half: the three numbers an archive's manifest has to agree with.
    resolve_and_link(policy::Expectations {
        abi_version,
        wire_version,
        abi_fingerprint: fingerprint,
    });
}

fn env_var(name: &str) -> String {
    std::env::var(name).unwrap_or_else(|e| panic!("cargo did not set {name}: {e}"))
}

/// Refuses to build when the vendored header is not the file the committed
/// digest describes.
///
/// This is the whole point of committing the digest. The header is the
/// contract and an edit to it that nobody noticed is an edit to the contract
/// that nobody noticed, so it fails here rather than three layers down as a
/// field reading its neighbour's bytes.
fn verify_digest(path: &Path, actual: &str) {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("I could not read {}: {e}", path.display()));
    let committed = text
        .split_whitespace()
        .next()
        .unwrap_or_else(|| panic!("{} is empty", path.display()));
    assert!(
        committed == actual,
        "the vendored header {HEADER} hashes to {actual}, and {} says it should hash to {committed}. \
         Either the header was edited without re-pinning it, or the pin was moved without copying \
         the header. Fix whichever one it is; do not update the digest to match.",
        path.display()
    );
}

/// One `#define NAME <decimal>` from the header, as the `u32` the generated
/// constants are typed as.
///
/// The parsing is `build/header.rs`, which `tests/` compiles too, so both
/// sides of the cross-check read the header the same way.
fn u32_define(header: &str, name: &str) -> u32 {
    let value = header::integer_define(header, name, HEADER);
    u32::try_from(value).unwrap_or_else(|_| {
        panic!("`#define {name} {value}` in {HEADER} does not fit a u32, and the header's own field for it is 32 bits wide")
    })
}

// ---------------------------------------------------------------------------
// Archive resolution and linking
//
// Issue #3 owns everything from here to the end of the file. The half above
// derives the three constants from the vendored header's bytes and belongs to
// the expectations lane; the only thing that crosses the line is the
// `Expectations` value `main` hands down, which is what this half compares an
// archive's manifest against.
//
// Nothing here reaches the network. An archive is already unpacked on disk or
// there is none, and `tests/build_script.rs` greps this file for the ways of
// asking for one.
// ---------------------------------------------------------------------------

/// Finds an archive, decides how to link it, and prints the lines that say so.
///
/// A missing archive is a warning and an absent `cfg`, never a failure, because
/// three of the five CI jobs never link one and the crate has to check, lint
/// and document without it. The one exception is a job that said out loud it
/// wants the native lane, through `ACADSHARP_REQUIRE_NATIVE`: there a missing
/// archive stops the build, because a lane that compiled out is the same colour
/// as a lane that passed.
fn resolve_and_link(expected: policy::Expectations) {
    let target = env_var("TARGET");
    // From the environment rather than through `cfg!`, which is what lets
    // `tests/build_script.rs` drive a feature combination without asking cargo
    // to build the whole crate again for each one.
    let features = policy::Features {
        link_static: std::env::var_os("CARGO_FEATURE_LINK_STATIC").is_some(),
        link_shared: std::env::var_os("CARGO_FEATURE_LINK_SHARED").is_some(),
    };

    let Some(root) = resolve_root(&target) else {
        return;
    };
    let archive = policy::Archive::at(root);

    let info = linkinfo::read(&archive.manifest).unwrap_or_else(|e| fail(&e.to_string()));
    let plan = policy::choose(&info, features, &target, expected, &archive)
        .unwrap_or_else(|e| fail(&e.to_string()));

    // Everything the plan is about to name has to actually be in the archive.
    // A truncated unpack otherwise turns into an undefined-symbol screen at the
    // end of somebody's link with nothing pointing at why.
    for relative in policy::required_files(&info, plan.kind) {
        if let Some(missing) = policy::missing_file(&archive, relative) {
            fail(&format!(
                "{} names {relative} and there is no such file at {}. The archive is incomplete, \
                 which `metadata/CHECKSUMS.txt` inside it is the way to check.",
                archive.manifest.display(),
                missing.display()
            ));
        }
    }

    println!("cargo::rerun-if-changed={}", archive.manifest.display());

    // Where a downstream build script picks these up, through cargo's `links`
    // key: `DEP_ACADSHARP_NATIVE_NATIVE_DIR` and friends.
    println!("cargo::metadata=native_dir={}", archive.root.display());
    println!("cargo::metadata=lib_dir={}", archive.lib_dir.display());
    println!("cargo::metadata=artifact_version={}", info.artifact_version);
    println!(
        "cargo::metadata=link_kind={}",
        match plan.kind {
            policy::LinkKind::Static => "static",
            policy::LinkKind::Shared => "shared",
        }
    );

    for directive in plan.directives() {
        println!("{directive}");
    }

    println!("cargo::rustc-cfg=acadsharp_linked");
    if plan.kind == policy::LinkKind::Static {
        // So a test that exists to prove the static link happened can gate on
        // the static link having happened, rather than on a feature that only
        // says it was asked for.
        println!("cargo::rustc-cfg=acadsharp_static_linked");
    }
}

/// `ACADSHARP_NATIVE_DIR`, then the cache, and nowhere else.
fn resolve_root(target: &str) -> Option<PathBuf> {
    if let Some(dir) = std::env::var_os("ACADSHARP_NATIVE_DIR") {
        let raw = PathBuf::from(&dir);

        // The raw variable first, before anything has had a chance to resolve
        // it away. Canonicalising follows symlinks, so checking only the
        // canonical path meant a link whose own name carried a newline pointed
        // at a perfectly clean directory, passed, and then came back out raw in
        // the warning `where_i_looked` prints. Measured: exit 0 and a
        // `cargo::rustc-link-arg=` of the caller's choosing on the next line.
        let raw_archive = policy::Archive::at(raw.clone());
        if let Err(e) = manifest::check_archive_root(&raw_archive.root, &raw_archive.manifest) {
            fail(&e.to_string());
        }

        // Canonical, because the rpath has to survive being read by a loader in
        // a different working directory than the one cargo built in.
        let root = raw.canonicalize().unwrap_or(raw);

        // And again on the canonical path, because that is the one the link
        // directives and the rpath carry, and a clean symlink can point at a
        // directory whose own name is not.
        let archive = policy::Archive::at(root);
        if let Err(e) = manifest::check_archive_root(&archive.root, &archive.manifest) {
            fail(&e.to_string());
        }

        if !archive.lib_dir.is_dir() {
            return give_up(
                target,
                &format!("{} has no lib/ directory", archive.root.display()),
            );
        }
        if !archive.manifest.is_file() {
            return give_up(
                target,
                &format!("{} has no metadata/LINKINFO.json", archive.root.display()),
            );
        }
        return Some(archive.root);
    }

    match cached_archives(target).as_slice() {
        [] => give_up(target, "ACADSHARP_NATIVE_DIR is unset"),
        [only] => {
            // Checked for the same reason as the variable above: this path is
            // built from a directory name somebody else chose.
            let archive = policy::Archive::at(only.clone());
            if let Err(e) = manifest::check_archive_root(&archive.root, &archive.manifest) {
                fail(&e.to_string());
            }
            Some(archive.root)
        }
        several => give_up(
            target,
            &format!(
                "ACADSHARP_NATIVE_DIR is unset and the cache holds {} archives for this target, \
                 so I will not guess which one you meant. Set ACADSHARP_NATIVE_DIR to one of \
                 them.",
                several.len()
            ),
        ),
    }
}

/// Every unpacked archive in the cache that is for this target.
///
/// The documented layout is
/// `$CARGO_HOME/acadsharp-native/<artifact_version>/<platform>-<cpu>/`, and the
/// version component is read from the directory rather than pinned, because the
/// pin it would need does not exist in this crate yet. That is safe in the one
/// direction that matters: a stale archive found here still has to get past the
/// ABI fingerprint comparison, which is the real check and which no amount of
/// directory naming can fake.
fn cached_archives(target: &str) -> Vec<PathBuf> {
    let (Some(root), Some(leaf)) = (cache_root(), policy::cache_leaf(target)) else {
        return Vec::new();
    };
    let Ok(entries) = std::fs::read_dir(&root) else {
        return Vec::new();
    };

    let mut found: Vec<PathBuf> = entries
        .filter_map(Result::ok)
        .map(|entry| entry.path().join(leaf))
        .filter(|candidate| candidate.join("metadata").join("LINKINFO.json").is_file())
        .collect();
    // `read_dir` hands entries back in whatever order the filesystem feels
    // like, so two archives in the cache would otherwise pick a different one
    // on different machines.
    found.sort();
    found
}

/// `$CARGO_HOME/acadsharp-native`, or the same under the default cargo home.
///
/// Checked for a control character here rather than at each call site, because
/// both call sites print it: `cached_archives` turns it into a
/// `rustc-link-search` by way of an archive it finds under there, and
/// `where_i_looked` puts it straight into the `cargo::warning=` line that the
/// no-archive path always prints. Nothing checked it at all before, so a
/// `CARGO_HOME` with a newline in it split that warning in two with the second
/// half a directive of the caller's choosing.
fn cache_root() -> Option<PathBuf> {
    let home = match std::env::var_os("CARGO_HOME") {
        Some(home) => PathBuf::from(home),
        None => PathBuf::from(std::env::var_os("HOME")?).join(".cargo"),
    };
    let root = home.join("acadsharp-native");
    if let Err(e) = manifest::check_cache_root(&root) {
        fail(&e.to_string());
    }
    Some(root)
}

/// Says there is no archive, in whichever of the two ways this build wants.
///
/// Always `None`, so a caller reads `return give_up(..)` as "there is nothing
/// here" without a second branch.
fn give_up(target: &str, why: &str) -> Option<PathBuf> {
    let where_i_looked = where_i_looked(target);
    if native_lane_required() {
        fail(&format!(
            "ACADSHARP_REQUIRE_NATIVE is set, so this build exists to link the native library, \
             and there is none: {why}. {where_i_looked}"
        ));
    }
    println!(
        "cargo::warning=no native archive resolved ({why}), so nothing is linked and every test \
         that calls the library is compiled out of this build. {where_i_looked}"
    );
    None
}

/// Both places an archive is looked for, and where one comes from.
fn where_i_looked(target: &str) -> String {
    let cache = match (cache_root(), policy::cache_leaf(target)) {
        (Some(root), Some(leaf)) => format!("{}/<artifact_version>/{leaf}/", root.display()),
        (Some(root), None) => format!(
            "{} (and nothing under it, because {target} is not a target the producer publishes \
             an archive for)",
            root.display()
        ),
        (None, _) => "the cache, whose location I could not work out with neither CARGO_HOME nor \
                      HOME set"
            .to_string(),
    };
    format!(
        "I looked in two places: ACADSHARP_NATIVE_DIR, which is {}, and the cache at {cache}. \
         An archive is a libviprs-dep release asset, unpacked; point the variable at the \
         directory holding lib/ and metadata/LINKINFO.json, or unpack one into the cache path \
         above. Nothing here downloads anything.",
        match std::env::var_os("ACADSHARP_NATIVE_DIR") {
            Some(dir) => format!("{}", PathBuf::from(dir).display()),
            None => "unset".to_string(),
        }
    )
}

/// Whether this build said out loud that it wants the native lane.
///
/// `Test` sets it as a job-level `env:`, where a step edit cannot lose it. An
/// empty value and a `0` both read as unset, so nobody has to remember which
/// spelling turns it off.
fn native_lane_required() -> bool {
    match std::env::var("ACADSHARP_REQUIRE_NATIVE") {
        Ok(value) => !value.is_empty() && value != "0",
        Err(_) => false,
    }
}

/// Stops the build, and says why in one piece.
fn fail(why: &str) -> ! {
    panic!("{why}");
}
