//! What the vendored header says, and whether the library agrees with it.
//!
//! Two halves, and they belong together. The three `EXPECTED_*` constants are
//! generated by `build.rs` from the bytes of `native/viprs_acadsharp.h`, and
//! [`check`] is the comparison that decides whether the library sitting behind
//! [`crate::ffi`] was built from that same header. Nothing else in the crate
//! should touch the library until it has passed.
//!
//! This is a leaf on purpose. The constants used to sit at the crate root and
//! `ffi::handshake` reached up for them, which points the dependency the wrong
//! way: `ffi` is a transcription of a C header and a transcription that reads
//! a constant out of its own parent is no longer one. Now `ffi` declares the
//! calls, this module decides what to do about their answers, and the root
//! re-exports the three constants so nothing downstream has to care that they
//! moved.
//!
//! # Why the two calls are not here
//!
//! This module holds no `unsafe` and links nothing. The two argument-free
//! calls that fetch the library's version and fingerprint live in the private
//! `sys` module with every other call, which is what makes "the one place
//! `unsafe` lives outside `ffi` is a private module" a true sentence rather
//! than a nearly true one, and what keeps `batch`, which is
//! `forbid(unsafe_code)`, from depending on the unsafe half through here.
//!
//! There used to be a `handshake` in this module, gated on
//! `any(acadsharp_linked, doc)`. The `doc` arm was there so docs.rs would show
//! it, and the effect of that was docs.rs advertising a public function that a
//! reader's own build, with no archive, does not have. That is exactly the
//! failure [`crate::Error::Unlinked`] exists to remove, and the reason for the
//! gate expired when [`crate::Decoder::new`] became the function a consumer
//! actually calls.
//!
//! [`check`] is ungated, takes the two numbers as arguments and calls nothing,
//! so the policy it holds is compiled, linted, documented and tested in every
//! job rather than in the one that has an archive. That matters more than it
//! sounds: before the split, changing the `&&` in the comparison to `||` broke
//! nothing that any archive-free job could see.

use core::fmt;

// EXPECTED_ABI_VERSION, EXPECTED_WIRE_VERSION and EXPECTED_ABI_FINGERPRINT,
// generated by build.rs from the bytes of native/viprs_acadsharp.h.
//
// This used to be a hand-written `pub const EXPECTED_ABI_VERSION: u32 = 1;`
// with a test asserting it equalled 1, which is a test that passes after any
// edit to the thing it is testing. The header says 2. Deriving it is the fix,
// and the tests that compare it with the header and with the library are the
// proof.
include!(concat!(env!("OUT_DIR"), "/abi_constants.rs"));

/// What the handshake found when the library and the vendored header disagree.
///
/// Both pairs are carried, not just the one that differed, because the pair
/// that matched is what tells you which kind of drift this is. Same version and
/// a different fingerprint means a comment-only edit or a rebuild from another
/// commit; different versions means the contract itself moved.
///
/// It is called `HeaderMismatch` rather than `AbiMismatch` because the crate
/// has a second thing by that name: a batch stream whose `wire_version` is not
/// the one this build parses. Both are real and they are not the same failure,
/// and the safe API has to fold both into one error type where a variant can
/// only mean one of them. The wire one keeps the contract's spelling; this one
/// is a Rust identifier and is free to say what it means.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub struct HeaderMismatch {
    /// The version the vendored header declares.
    pub expected_abi_version: u32,
    /// The version the library reports.
    pub actual_abi_version: u32,
    /// The fingerprint of the vendored header.
    pub expected_fingerprint: u64,
    /// The fingerprint the library reports.
    pub actual_fingerprint: u64,
}

impl fmt::Display for HeaderMismatch {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "the native library does not match the header this crate was built against: \
             it reports ABI version {} and fingerprint {:#018x}, and the header declares \
             version {} and fingerprint {:#018x}",
            self.actual_abi_version,
            self.actual_fingerprint,
            self.expected_abi_version,
            self.expected_fingerprint
        )
    }
}

impl std::error::Error for HeaderMismatch {}

/// Compares what a library reports with what the vendored header declares.
///
/// The version is the coarse check and the fingerprint is the fine one, and
/// both have to match. They differ exactly when the header and the library
/// came from different commits, which is the failure worth catching: the
/// library loads, every symbol resolves, and a struct field sits four bytes
/// from where this crate believes it is.
///
/// This takes the two numbers rather than fetching them, so it is a plain
/// function over two integers with no linkage, no `unsafe` and no environment
/// behind it. Fetching them is `sys`'s job, because that is where every call
/// into the library lives, and [`crate::Decoder::new`] is what runs the pair.
///
/// ```
/// use acadsharp_rs::abi::{self, EXPECTED_ABI_FINGERPRINT, EXPECTED_ABI_VERSION};
///
/// assert!(abi::check(EXPECTED_ABI_VERSION, EXPECTED_ABI_FINGERPRINT).is_ok());
///
/// // One bit out of the fingerprint is a different header, so it is refused.
/// let refused = abi::check(EXPECTED_ABI_VERSION, EXPECTED_ABI_FINGERPRINT ^ 1).unwrap_err();
/// assert_eq!(refused.actual_abi_version, EXPECTED_ABI_VERSION);
/// ```
pub fn check(actual_version: u32, actual_fingerprint: u64) -> Result<(), HeaderMismatch> {
    if actual_version == EXPECTED_ABI_VERSION && actual_fingerprint == EXPECTED_ABI_FINGERPRINT {
        return Ok(());
    }

    Err(HeaderMismatch {
        expected_abi_version: EXPECTED_ABI_VERSION,
        actual_abi_version: actual_version,
        expected_fingerprint: EXPECTED_ABI_FINGERPRINT,
        actual_fingerprint,
    })
}
