//! Safe Rust decoder for DWG, backed by the ACadSharp NativeAOT artifacts
//! published by [`libviprs-dep`].
//!
//! The safe API is still being built. What exists today is [`ffi`], the raw
//! transcription of `viprs_acadsharp.h`, and the three constants below that
//! pin this crate to one version of that header.
//!
//! The boundary this crate owns: it exposes a safe, idiomatic Rust API and
//! never lets .NET or ACadSharp internals reach its callers.
//!
//! # The header is vendored, and the constants are derived from it
//!
//! `native/viprs_acadsharp.h` is a byte-for-byte copy of the frozen header,
//! pinned to the `libviprs-dep` commit named in `native/NATIVE_HEADER_REV` and
//! hashed in `native/viprs_acadsharp.h.sha256`. The build script refuses to
//! build if those two disagree.
//!
//! [`EXPECTED_ABI_VERSION`], [`EXPECTED_WIRE_VERSION`] and
//! [`EXPECTED_ABI_FINGERPRINT`] are generated from that file's bytes at build
//! time. Nobody types them, so nothing in the crate can go on agreeing with a
//! header that moved.
//!
//! # Linking the native library
//!
//! Point `ACADSHARP_NATIVE_DIR` at an unpacked `libviprs-dep` archive, the
//! directory holding `lib/` and `metadata/LINKINFO.json`, and the build script
//! emits the link lines and sets `cfg(acadsharp_linked)`. With no archive the
//! crate still builds, checks and documents; everything that calls the library
//! is simply compiled out.
//!
//! [`libviprs-dep`]: https://github.com/libviprs/libviprs-dep
#![forbid(unsafe_op_in_unsafe_fn)]

pub mod ffi;

// EXPECTED_ABI_VERSION, EXPECTED_WIRE_VERSION and EXPECTED_ABI_FINGERPRINT,
// generated by build.rs from the bytes of native/viprs_acadsharp.h.
//
// This used to be a hand-written `pub const EXPECTED_ABI_VERSION: u32 = 1;`
// with a test asserting it equalled 1, which is a test that passes after any
// edit to the thing it is testing. The header says 2. Deriving it is the fix,
// and the tests that compare it with the header and with the library are the
// proof.
include!(concat!(env!("OUT_DIR"), "/abi_constants.rs"));
